[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
ParSitter = "bdeffda0-9f75-4d6c-9dad-1bfd8db84b8f"
